---
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: poetry run black
        types: [python]

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        language: system
        entry: poetry run autoflake --expand-star-imports --remove-all-unused-imports --remove-unused-variables --in-place --recursive tests/ cruft_helloworld/
        types: [python]

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        language: system
        entry: poetry run autoflake --expand-star-imports --remove-all-unused-imports --remove-unused-variables --in-place --recursive tests/ cruft_helloworld/
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: poetry run isort
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: poetry run mypy
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: poetry run flake8
        types: [python]

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.14.2
    hooks:
      - id: validate_manifest
