[gh-actions]
python =
  3.8: py38
  3.9: py39
  3.10: py310
  3.11: py311
  3.12: py312

[tox]
skipsdist = True
isolated_build = True
envlist =
  py38
  py39
  py310
  py311
  py312
skip_missing_interpreters = True


[testenv]
skip_install = True
whitelist_externals =
  bash
  env
  grep
deps =
  poetry
commands =
  poetry install
  poetry run pytest --cov=cruft_helloworld --cov-report term
